# Generated by Django 5.2 on 2025-04-26 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_rlproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='RLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('DQN', 'Deep Q-Network'), ('PPO', 'Proximal Policy Optimization')], max_length=10)),
                ('model_file', models.FileField(upload_to='rl_models/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['product__name', 'algorithm'],
                'unique_together': {('product', 'algorithm')},
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('successful', models.BooleanField(default=False)),
                ('log_output', models.TextField(blank=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='rl_pricing.rlmodel')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
