# Generated by Django 5.2 on 2025-04-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RLProduct',
            fields=[
            ],
            options={
                'verbose_name': 'RL Product Model',
                'verbose_name_plural': 'RL Product Models',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
