# Generated by Django 5.2 on 2025-04-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rlproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RLProduct',
        ),
    ]
