# Generated by Django 5.2 on 2025-04-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_rlproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricehistory',
            name='change_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
