# Generated by Django 5.2 on 2025-04-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_last_strategy_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ab_group',
            field=models.CharField(choices=[('A', 'Traditional Static Pricing'), ('B', 'Reinforcement Learning Pricing')], default='A', help_text='A = Static Pricing, B = RL Pricing', max_length=1),
        ),
    ]
