# Generated by Django 5.2 on 2025-04-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_ab_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricehistory',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
