# Generated by Django 5.2 on 2025-04-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productpricehistory_revenue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ab_group',
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing_strategy',
            field=models.CharField(choices=[('RL', 'Reinforcement Learning Pricing'), ('STATIC', 'Traditional Static Pricing')], default='RL', help_text='RL = Reinforcement Learning Pricing, STATIC = Traditional Static Pricing', max_length=10),
        ),
    ]
